basePath: /api
definitions:
  model.CreateOrGetPrivateRoomRequest:
    properties:
      target_user_id:
        type: string
    type: object
  model.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.ProfileResponse:
    properties:
      avatar:
        type: string
      bio:
        type: string
      username:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  model.UpdateProfileRequest:
    properties:
      avatar:
        type: string
      bio:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: arya@example.com
    name: Arya Prodigy
  description: API WEBCHAT
  termsOfService: http://swagger.io/terms/
  title: Webchat
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Masukan username & password untuk mendapatkan token JWT
      parameters:
      - description: Username & Password
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login User
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Menghasilkan access token baru menggunakan refresh token dari cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh Access Token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Membuat akun baru untuk mengakses API yang diproteksi
      parameters:
      - description: Username & Password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Daftar User WebSystem
      tags:
      - Auth
  /chat/private:
    post:
      consumes:
      - application/json
      description: Check existing private room between users or create new one
      parameters:
      - description: Target User ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateOrGetPrivateRoomRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get or Create Private Room
      tags:
      - Chat
  /profile/avatar:
    patch:
      consumes:
      - multipart/form-data
      description: Upload dan update avatar user yang sedang login
      parameters:
      - description: Avatar Image (jpg/png)
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update Avatar
      tags:
      - Profile
  /profile/me:
    get:
      consumes:
      - application/json
      description: Mengambil data profile user yang sedang login (berdasarkan JWT)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProfileResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get My Profile
      tags:
      - Profile
    patch:
      consumes:
      - application/json
      description: Update username, bio, atau avatar user yang sedang login
      parameters:
      - description: Update Profile Data
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/model.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update My Profile
      tags:
      - Profile
  /profile/update/{id}:
    patch:
      consumes:
      - application/json
      description: Memperbarui username, bio, atau avatar berdasarkan User ID
      parameters:
      - description: User UUID
        in: path
        name: id
        required: true
        type: string
      - description: Update Profile Data
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/model.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil memperbarui profil
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Format ID atau Request tidak valid
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update User Profile
      tags:
      - Profile
  /users:
    get:
      consumes:
      - application/json
      description: Mengambil daftar semua user (tanpa detail)
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get semua user
      tags:
      - Users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Mengambil detail user berdasarkan ID
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get detail user
      tags:
      - Users
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: 'Masukkan token dengan format: Bearer <token_kamu>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
