name: mobile_flutter
description: "Signal Chat App - UTS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  web_socket_channel: ^3.0.3
  intl: ^0.20.2
  google_fonts: ^8.0.2
  lottie: ^3.3.3
  shared_preferences: ^2.5.5
  dio: ^5.9.2
  provider: ^6.1.5+1
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_splash.png
    - assets/animations/logo_splash.json