name: CI

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-go

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - run: go mod tidy
      - run: go test ./...

      - name: Build Docker
        run: docker build -t app .

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile_flutter

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - run: flutter pub get
      - run: flutter test